// integracao-react/src/componentes/Contador.tsx
import React, { Component } from "react";
import ContadorValor from "./ContadorValor";

import logRender from "../decorators/logRender";

interface IContadorProps {
  valorInicial?: number
}

interface IContadorState {
  valor: number
}

@logRender
export default class Contador extends Component<IContadorProps, IContadorState> {
  public state = { valor: this.props.valorInicial || 0}

  private setValor = (delta: number) => {
    this.setState({
      valor: this.state.valor + delta
    });
  }

  render() {
    return (
      <div>
        <ContadorValor contador={this.state.valor}/>
        <button onClick={() => this.setValor(1)}>+</button>
        <button onClick={() => this.setValor(-1)}>-</button>
      </div>
    );
  }
}

// integracao-vue/src/components/Contador.vue
<template>
  <div>
    <h1>Contador</h1>
    <h2>{{ valor }}</h2>
    <button @click="setValor(-1)">Decrementar</button>
    <button @click="setValor(1)">Incremento</button>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: "Contador-personalizado",
  props: {
    valorInicial: {
      type: Number,
    }
  },
  data() {
    return {
      valor: this.valorInicial
    }
  },
  methods: {
    setValor(delta: number) {
      this.valor += delta;
    }
  }
})
</script>

<style scoped>

</style>
